# Generated by Django 5.0.6 on 2024-06-10 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payslip',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='friday',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='monday',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='saturday',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='sunday',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='thursday',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='tuesday',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='wednesday',
        ),
        migrations.AddField(
            model_name='schedule',
            name='friday_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='friday_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='monday_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='monday_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='saturday_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='saturday_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='sunday_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='sunday_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='thursday_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='thursday_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='tuesday_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='tuesday_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='wednesday_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='wednesday_start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
