# Generated by Django 5.0.6 on 2024-05-31 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='attendance',
            name='salary_computation',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
