# Generated by Django 5.0.6 on 2024-05-30 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='salary',
        ),
    ]
