# Generated by Django 5.0.6 on 2024-06-01 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_attendance_salary_attendance_salary_computation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('middle_initial', models.CharField(blank=True, max_length=1)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('contact_number', models.CharField(max_length=15)),
                ('deployment', models.CharField(max_length=100)),
                ('occupation', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='email',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='status',
        ),
        migrations.AddField(
            model_name='attendance',
            name='on_duty',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=450, max_digits=10),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='time_in',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='time_out',
            field=models.TimeField(),
        ),
        migrations.AddField(
            model_name='attendance',
            name='employee_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.employee'),
        ),
        migrations.CreateModel(
            name='PaySlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('employee_name', models.CharField(max_length=100)),
                ('total_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid', models.BooleanField(default=False)),
                ('employee_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.employee')),
            ],
        ),
    ]
