# Generated by Django 5.0.6 on 2024-06-07 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_delete_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='working_hours',
            field=models.CharField(default='0 0', max_length=50),
        ),
    ]
