# Generated by Django 5.0.6 on 2024-06-01 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_attendance_date_alter_attendance_time_in_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='employee_ID',
        ),
        migrations.AddField(
            model_name='attendance',
            name='employeeID',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='attendance',
            name='employee_Name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=450, max_digits=10),
        ),
    ]
