# Generated by Django 5.0.6 on 2024-06-01 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_remove_attendance_employee_id_attendance_employeeid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payslip',
            name='employee_ID',
        ),
        migrations.AddField(
            model_name='payslip',
            name='employeeID',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
