# Generated by Django 5.0.6 on 2024-06-05 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_companyid_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='companyID',
        ),
    ]
